# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acafaaf368c455516c4ea477e84c47aa4d9bfe679ae2f7f7531b3bc4fb26e2a619b78fae5824d62fdad16baa89e7c69c770348e198d285550b34873a05c5f836

test:
  secret_key_base: fd285d20ca8bd36f6e5a661e5e883ffee94880860245dba0b03ceba8cf98a42962bfa297dab3bff7c5389d968c673b784c4698d87b82628713c27f5c187b1a9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
